name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ununtu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
